name: Test

on:
    push:
      branches:
        - "**"
    pull_request:

jobs:
    flake8:
        name: flake8
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3.x
          uses: actions/setup-python@v5
          with:
            python-version: ">=3.7 <3.13"
            cache: 'pip'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
        - name: Run flake8
          run: flake8 AutoBanana.py
